import { asRecord, asRecords, readNumber, readText } from './journey';
import type { JsonRecord } from '../types/domain';

export const LEVELS = { BEGINNER: 'Người mới', INTERMEDIATE: 'Trung cấp', ADVANCED: 'Nâng cao' };
export const TRACKING = { STRENGTH: 'Sức mạnh', BODYWEIGHT: 'Trọng lượng cơ thể', CARDIO: 'Cardio', INTERVAL: 'Tập ngắt quãng', MOBILITY: 'Linh hoạt' };
export const PRESCRIPTIONS: Record<string, [string, string, string?][]> = {
  STRENGTH: [['sets', 'Sets'], ['reps', 'Reps'], ['targetWeight', 'Weight', 'kg'], ['restSeconds', 'Rest', 's'], ['targetRpe', 'RPE'], ['targetRir', 'RIR']],
  BODYWEIGHT: [['sets', 'Sets'], ['reps', 'Reps'], ['addedWeight', 'Added Weight', 'kg'], ['restSeconds', 'Rest', 's'], ['targetRpe', 'RPE'], ['targetRir', 'RIR']],
  CARDIO: [['durationMinutes', 'Duration', 'min'], ['distanceKm', 'Distance', 'km'], ['targetPaceSecondsPerKm', 'Pace', 's/km'], ['targetHeartRate', 'Heart Rate', 'bpm'], ['inclinePercent', 'Incline', '%'], ['targetRpe', 'RPE']],
  INTERVAL: [['rounds', 'Rounds'], ['workSeconds', 'Work Time', 's'], ['restSeconds', 'Rest', 's'], ['distanceMetersPerRound', 'Distance/Round', 'm'], ['repsPerRound', 'Reps/Round'], ['targetRpe', 'RPE']],
  MOBILITY: [['durationMinutes', 'Duration', 'min'], ['reps', 'Reps'], ['side', 'Side (LEFT / RIGHT / BOTH)'], ['targetDiscomfort', 'Discomfort Level']],
};
export function recordId(record: unknown): string { return readText(record, ['_id', 'id']); }
export interface WorkoutDay { key: string; name: string; exercises: JsonRecord[] }
export function workoutDays(plan: JsonRecord): WorkoutDay[] {
  const scheduled = asRecords(plan.scheduledExercises);
  // Preserve weeks and times: legacy sessions generated by the web API can merge weeks.
  if (scheduled.length) {
    const groups = new Map<string, WorkoutDay>();
    for (const exercise of [...scheduled].sort((a, b) => (readNumber(a, ['weekNumber']) ?? 1) - (readNumber(b, ['weekNumber']) ?? 1) || (readNumber(a, ['dayNumber']) ?? 1) - (readNumber(b, ['dayNumber']) ?? 1) || (readNumber(a, ['startMinute']) ?? 0) - (readNumber(b, ['startMinute']) ?? 0))) {
      const week = readNumber(exercise, ['weekNumber']) ?? 1;
      const day = readNumber(exercise, ['dayNumber']) ?? 1;
      const key = `${week}:${day}`;
      if (!groups.has(key)) groups.set(key, { key, name: `Tuần ${week} · Ngày ${day}`, exercises: [] });
      groups.get(key)!.exercises.push(exercise);
    }
    return [...groups.values()];
  }
  return asRecords(plan.sessions).map((session, index) => ({ key: `session-${index}`, name: readText(session, ['name'], `Buổi ${index + 1}`), exercises: asRecords(session.exercises) }));
}
export function exerciseMetrics(exercise: JsonRecord): [string, string][] {
  const prescription = asRecord(exercise.prescription);
  const fields = PRESCRIPTIONS[readText(exercise, ['trackingType'])] || PRESCRIPTIONS.STRENGTH;
  const aliases: Record<string, string> = { targetWeight: 'weight', targetRpe: 'rpe', targetRir: 'rir' };
  const result: [string, string][] = [];
  for (const [key, label, unit] of fields) {
    const value = readText(prescription, [key]) || readText(exercise, [aliases[key] || key]);
    if (value) result.push([label, `${value}${unit ? ` ${unit}` : ''}`]);
    else if (key === 'restSeconds' && readText(exercise, ['rest'])) result.push([label, readText(exercise, ['rest'])]);
  }
  const tempo = readText(exercise, ['tempo']);
  if (tempo) result.push(['Tempo', tempo]);
  return result;
}
export function customerPlans(value: unknown): JsonRecord[] {
  const state = asRecord(value);
  const candidates = [state.active, ...asRecords(state.published), ...asRecords(state.history)];
  const seen = new Set<string>();
  return candidates.filter((item): item is JsonRecord => {
    const plan = asRecord(item); const id = recordId(plan);
    if (!id || plan.status !== 'PUBLISHED' || seen.has(id)) return false;
    seen.add(id); return true;
  });
}
const metadata = ['title', 'goal', 'level', 'durationDays', 'muscleGroups', 'defaultSets', 'defaultReps', 'defaultWeight', 'defaultTempo', 'technicalNotes'];
const exerciseFields = ['exerciseId', 'name', 'trackingType', 'prescription', 'sets', 'reps', 'weight', 'rpe', 'rir', 'tempo', 'restSeconds', 'notes'];
function pick(source: JsonRecord, keys: string[]): JsonRecord {
  return Object.fromEntries(keys.filter((key) => source[key] !== undefined).map((key) => [key, source[key]]));
}
export function planPayload(draft: JsonRecord): JsonRecord {
  if (!readText(draft, ['title'])) throw new Error('Vui lòng nhập tên giáo án.');
  const payload = pick(draft, metadata);
  payload.title = readText(draft, ['title']);
  if (!readText(draft, ['goal'])) throw new Error('Vui lòng nhập mục tiêu giáo án.');
  payload.goal = readText(draft, ['goal']);
  if (!Object.keys(LEVELS).includes(readText(draft, ['level']))) throw new Error('Vui lòng chọn cấp độ.');
  if (payload.durationDays !== undefined) {
    const days = Number(payload.durationDays);
    if (!Number.isInteger(days) || days < 1 || days > 365) throw new Error('Số ngày phải từ 1 đến 365.');
    payload.durationDays = days;
  }
  if (payload.defaultSets !== undefined && (!Number.isInteger(Number(payload.defaultSets)) || Number(payload.defaultSets) < 1 || Number(payload.defaultSets) > 100)) throw new Error('Số hiệp mặc định phải từ 1 đến 100.');
  const scheduledItems = asRecords(draft.scheduledExercises);
  for (const item of scheduledItems) {
    const week = Number(item.weekNumber ?? 1), day = Number(item.dayNumber), start = Number(item.startMinute), duration = Number(item.durationMinutes);
    if (!Number.isInteger(week) || week < 1 || !Number.isInteger(day) || day < 1 || day > 7 || !Number.isInteger(start) || start < 0 || start > 1425 || start % 15 !== 0 || !Number.isInteger(duration) || duration < 15 || duration % 15 !== 0 || start + duration > 1440) throw new Error('Giờ bắt đầu và thời lượng phải theo bước 15 phút, nằm trong ngày.');
  }
  const ordered = [...scheduledItems].sort((a, b) => Number(a.weekNumber ?? 1) - Number(b.weekNumber ?? 1) || Number(a.dayNumber) - Number(b.dayNumber) || Number(a.startMinute) - Number(b.startMinute));
  for (let i = 1; i < ordered.length; i++) {
    const previous = ordered[i - 1], current = ordered[i];
    if (Number(previous.weekNumber ?? 1) === Number(current.weekNumber ?? 1) && Number(previous.dayNumber) === Number(current.dayNumber) && Number(current.startMinute) < Number(previous.startMinute) + Number(previous.durationMinutes)) throw new Error('Các bài tập trong cùng ngày không được trùng thời gian.');
  }
  const cleanExercise = (exercise: JsonRecord, extra: string[] = []) => {
    if (!readText(exercise, ['name'])) throw new Error('Vui lòng nhập tên cho tất cả bài tập.');
    const kind = readText(exercise, ['trackingType']);
    if (!PRESCRIPTIONS[kind]) throw new Error(`Chọn cách ghi nhận cho bài ${exercise.name}.`);
    const prescription: JsonRecord = {};
    for (const [key] of PRESCRIPTIONS[kind]) {
      const raw = asRecord(exercise.prescription)[key];
      if (raw === undefined || raw === '') continue;
      if (key === 'side') {
        const side = String(raw).trim().toUpperCase();
        if (!['LEFT', 'RIGHT', 'BOTH'].includes(side)) throw new Error('Bên tập phải là LEFT, RIGHT hoặc BOTH.');
        prescription[key] = side;
      } else if (key === 'reps' && kind !== 'MOBILITY') prescription[key] = String(raw);
      else {
        const number = Number(raw);
        const positive = ['sets', 'rounds', 'durationMinutes', 'distanceKm', 'targetPaceSecondsPerKm', 'targetHeartRate', 'workSeconds', 'distanceMetersPerRound', 'repsPerRound', 'reps'].includes(key);
        if (!Number.isFinite(number) || number < 0 || (positive && number === 0) || (['sets', 'rounds', 'repsPerRound', 'reps'].includes(key) && !Number.isInteger(number)) || (['targetRpe', 'targetDiscomfort'].includes(key) && number > 10)) throw new Error(`Thông số không hợp lệ cho bài ${exercise.name}.`);
        prescription[key] = number;
      }
    }
    const result = { ...pick(exercise, [...exerciseFields, ...extra]), name: readText(exercise, ['name']), prescription } as JsonRecord;
    // Keep the web portal's legacy display fields in sync with typed prescriptions.
    const legacy: Record<string, string> = { sets: 'sets', reps: 'reps', targetWeight: 'weight', addedWeight: 'weight', targetRpe: 'rpe', targetRir: 'rir', restSeconds: 'restSeconds' };
    for (const [key, target] of Object.entries(legacy)) {
      if (PRESCRIPTIONS[kind].some(([field]) => field === key)) {
        delete result[target];
        if (prescription[key] !== undefined) result[target] = target === 'weight' || target === 'reps' ? String(prescription[key]) : prescription[key];
      }
    }
    return result;
  };
  if (asRecords(draft.scheduledExercises).length) {
    for (const item of asRecords(draft.scheduledExercises)) {
      if ((Number(item.weekNumber || 1) - 1) * 7 + Number(item.dayNumber) > Number(payload.durationDays)) throw new Error('Số ngày giáo án không được ngắn hơn lịch bài tập đã xếp.');
    }
    payload.scheduledExercises = asRecords(draft.scheduledExercises).map((item) => cleanExercise(item, ['weekNumber', 'dayNumber', 'startMinute', 'durationMinutes']));
  } else {
    const sessions = asRecords(draft.sessions);
    if (!sessions.length) throw new Error('Giáo án cần ít nhất một buổi tập.');
    payload.sessions = sessions.map((session) => {
      if (!readText(session, ['name']) || !asRecords(session.exercises).length) throw new Error('Mỗi buổi cần tên và ít nhất một bài tập.');
      return { name: readText(session, ['name']), exercises: asRecords(session.exercises).map((item) => cleanExercise(item)) };
    });
  }
  if (Array.isArray(draft.unscheduledExercises)) payload.unscheduledExercises = asRecords(draft.unscheduledExercises).map((item) => cleanExercise(item, ['durationMinutes']));
  if (asRecords(draft.generatedExercises).length) payload.generatedExercises = asRecords(draft.generatedExercises);
  return payload;
}

export function prepareDraft(plan: JsonRecord): JsonRecord {
  const draft: JsonRecord = JSON.parse(JSON.stringify(plan));
  function prepare(exercise: JsonRecord): JsonRecord {
    const kind = readText(exercise, ['trackingType']);
    const prescription = { ...asRecord(exercise.prescription) };
    const aliases: Record<string, string> = { targetWeight: 'weight', addedWeight: 'weight', targetRpe: 'rpe', targetRir: 'rir' };
    for (const [key] of PRESCRIPTIONS[kind] || []) {
      if (prescription[key] !== undefined) continue;
      const raw = exercise[aliases[key] || key] ?? (key === 'restSeconds' ? exercise.rest : undefined);
      if (raw === undefined || raw === null || raw === '') continue;
      if (key === 'reps' && kind !== 'MOBILITY') prescription[key] = String(raw);
      else if (key === 'side') prescription[key] = raw;
      else if (Number.isFinite(Number(raw))) prescription[key] = Number(raw);
    }
    return { ...exercise, prescription };
  }
  if (Array.isArray(draft.sessions)) draft.sessions = asRecords(draft.sessions).map((session) => ({ ...session, exercises: asRecords(session.exercises).map(prepare) }));
  for (const field of ['scheduledExercises', 'unscheduledExercises']) if (Array.isArray(draft[field])) draft[field] = asRecords(draft[field]).map(prepare);
  return draft;
}
